package llama

import (
	"errors"
	"time"

	"github.com/arandu-io/framework/data"
	"github.com/arandu-io/hesape/database/model"
)

// Llama is the entity this package owns: one scored measurement of a model.
//
// A reading is what an inference engine produces when it is asked what a
// sequence costs rather than what comes next -- the negative log likelihood the
// model assigns to text it did not write.
//
// Keeping them is not bookkeeping. A twenty-step training run once reported the
// same loss at every step because the measurement was reading a model with no
// adapter applied, and telling that apart from a run that had converged needed
// the readings side by side. A run that keeps its numbers in a variable has
// nothing to put side by side.
//
// It embeds the model, so a row returned by a query carries the connection and
// can be saved again. Build new rows through Llamas: a struct literal has no
// connection and its write methods return model.ErrUnwired.
type Llama struct {
	model.Model[Llama]

	// ID is the identifier. It is generated by the application rather than by
	// the database, because a DEFAULT that produces a uuid is spelled
	// differently in every engine.
	ID string `db:"id"`

	// TenantID is the customer the row belongs to. It is written from the
	// Grant and read back so the policy can compare it against the subject's
	// tenant.
	TenantID string `db:"tenant_id"`

	// Name is what a person calls this record.
	Name string `db:"name"`

	// Subject identifies what was scored: the example, task or prompt. It is a
	// name from the caller's own vocabulary, because this package does not own
	// the corpus and should not pretend to.
	Subject string `db:"subject"`

	// Policy is the digest of the adapter applied when the reading was taken.
	// Two readings of the same subject under different policies are the only
	// comparison that means anything, and a reading that cannot say which policy
	// produced it cannot enter one.
	Policy string `db:"policy"`

	// Quantisation is the representation the weights were in: Q4_K_M, Q2_K, F16.
	// It is a column and not a note because the question this package exists to
	// answer is what a lower bit-width costs, and that question is a comparison
	// across this field with everything else held equal.
	Quantisation string `db:"quantisation"`

	// Loss is the summed negative log likelihood, and Tokens is how many
	// positions it covers. They are stored apart rather than as a mean because a
	// caller averaging several readings has to weight each by its length;
	// averaging the means over-weights short subjects silently.
	Loss   float64 `db:"loss"`
	Tokens int     `db:"tokens"`

	// Milliseconds is how long the engine took. It is here because the cost of a
	// reading is half of every decision made from one.
	Milliseconds int64 `db:"milliseconds"`

	// CreatedAt is when the row was written, in UTC.
	CreatedAt time.Time `db:"created_at"`
}

// Llamas returns the configured model for the llamas table.
//
// The primary key is application-generated text, so it does not increment.
// The tenant scope remains on the model's tenant_id default.
func Llamas(db *data.DB) *model.Model[Llama] {
	m := model.NewModel[Llama]("llamas", db, db.GetQueryGrammar(), db.GetPostProcessor())
	m.KeyType = "string"
	m.Incrementing = false
	return m
}

// ErrNotFound is returned when no row matches, including when the row exists
// in another tenant. The two cases are deliberately indistinguishable.
var ErrNotFound = errors.New("llama: record not found")

// Resource is the list of fields one Llama is allowed to answer with.
//
// A declared list rather than the entity itself. An encoder handed the entity
// answers with whatever fields it happens to have, including the ones somebody
// adds later without ever opening the handler -- and TenantID is exactly such a
// field: it names another customer's identifier and belongs in no response.
type Resource struct {
	id           string
	name         string
	subject      string
	policy       string
	quantisation string
	loss         float64
	tokens       int
	milliseconds int64
	createdAt    time.Time
}

// NewResource snapshots one record for the response.
func NewResource(record Llama) Resource {
	return newResource(record)
}

func resourceFromPointer(record *Llama) Resource {
	if record == nil {
		return Resource{}
	}
	return newResource(*record)
}

func newResource(record Llama) Resource {
	return Resource{
		id: record.ID, name: record.Name, subject: record.Subject,
		policy: record.Policy, quantisation: record.Quantisation,
		loss: record.Loss, tokens: record.Tokens,
		milliseconds: record.Milliseconds, createdAt: record.CreatedAt,
	}
}

// ToArray returns the fields that may leave, by name.
func (r Resource) ToArray() map[string]any {
	// The mean is computed here rather than stored, so the sum and the count stay
	// the record and the average stays a convenience. A reader combining readings
	// uses the two; a reader wanting one number gets it without having to know
	// that.
	mean := 0.0
	if r.tokens > 0 {
		mean = r.loss / float64(r.tokens)
	}
	return map[string]any{
		"id":           r.id,
		"name":         r.name,
		"subject":      r.subject,
		"policy":       r.policy,
		"quantisation": r.quantisation,
		"loss":         r.loss,
		"tokens":       r.tokens,
		"mean":         mean,
		"milliseconds": r.milliseconds,
		"created_at":   r.createdAt.UTC().Format(time.RFC3339),
	}
}

// With returns what goes beside the fields at the top level of the response.
// Nothing does here, and a resource that has nothing to add says so by
// answering nil.
func (r Resource) With() map[string]any { return nil }

// Collection is a page of records as one response.
type Collection struct {
	records []Resource
	// cursor is what the next page asks for, empty when this page is the last
	// one. It goes beside the items rather than inside them: it describes the
	// answer, not the things answered with.
	cursor string
}

// NewCollection wraps a page of records for the response. The cursor is what
// the next request passes back, and is empty when there is no next page.
func NewCollection(records []Llama, cursor string) Collection {
	resources := make([]Resource, 0, len(records))
	for _, record := range records {
		resources = append(resources, NewResource(record))
	}
	return Collection{records: resources, cursor: cursor}
}

// collectionFromPointers takes the Model-backed rows returned by a terminal
// and snapshots only what the response reads. The public constructor keeps its
// value-based API for callers that build resources without touching storage.
func collectionFromPointers(records []*Llama, cursor string) Collection {
	resources := make([]Resource, 0, len(records))
	for _, record := range records {
		if record != nil {
			resources = append(resources, resourceFromPointer(record))
		}
	}
	return Collection{records: resources, cursor: cursor}
}

// ToArray returns the page under a single key, so that the shape of the
// response does not change when a second key is added beside it.
func (c Collection) ToArray() map[string]any {
	items := make([]map[string]any, 0, len(c.records))
	for _, record := range c.records {
		items = append(items, record.ToArray())
	}
	return map[string]any{"items": items}
}

// With returns the cursor of the next page, and nothing when there is none.
func (c Collection) With() map[string]any {
	if c.cursor == "" {
		return nil
	}
	return map[string]any{"next_cursor": c.cursor}
}
