package decoder

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"math"
	"strings"

	"github.com/tayi-ai/arandu-llama/training/torch"
)

// ErrInitialAdapterSpec identifies an absent identity or invalid bounded input.
var ErrInitialAdapterSpec = errors.New("decoder: invalid initial adapter specification")

// ErrInitialAdapterIdentity means generated bytes differ from the caller's
// mandatory expected digest. No tensors are returned on this failure.
var ErrInitialAdapterIdentity = errors.New("decoder: initial adapter identity differs")

// InitialProjection declares one low-rank projection and its stable parameter prefix.
type InitialProjection struct {
	Name                string
	Input, Output, Rank int64
}

// InitialAdapterSpec supplies every shape, stream operation and identity.
// Prelude blocks represent explicitly admitted reference stream consumption.
// No random schedule or aggregate digest is inferred from a model name.
type InitialAdapterSpec struct {
	Seed                    uint64
	PreludeBlocks           int
	PreludeWidth            int64
	PreludeLow, PreludeHigh float64
	Projections             []InitialProjection
	ExpectedSHA256          string
}

// InitialParameter owns one named, trainable FP32 CPU leaf. Names follow the
// preserved PEFT namespace; the caller owns any later placement or conversion.
type InitialParameter struct {
	Name  string
	Value *torch.Tensor
}

// InitialAdapter owns the explicitly requested FP32 projection tensors.
// SHA256 hashes each UTF-8 name followed by its contiguous FP32 CPU bytes, in
// parameter order (layer, q/v projection, A/B). It qualifies initial bytes only.
type InitialAdapter struct {
	Parameters []InitialParameter
	SHA256     string
}

// Close releases every owned parameter and is idempotent, including nil values.
func (a *InitialAdapter) Close() error {
	if a == nil {
		return nil
	}
	var failures []error
	for _, parameter := range a.Parameters {
		failures = append(failures, parameter.Value.Close())
	}
	a.Parameters = nil
	return errors.Join(failures...)
}

// InitializeAdapter reproduces an admitted CPU initialization schedule using a
// private generator. Each projection consumes constructor A and B draws, resets
// A with the inverse-square-root input bound and sets B to exact positive zero.
// The mandatory aggregate digest rejects an unqualified schedule or backend.
func InitializeAdapter(ctx context.Context, spec InitialAdapterSpec) (_ *InitialAdapter, err error) {
	if ctx == nil || spec.PreludeBlocks < 0 || spec.PreludeBlocks > 4096 || len(spec.ExpectedSHA256) != 64 || strings.ToLower(spec.ExpectedSHA256) != spec.ExpectedSHA256 {
		return nil, ErrInitialAdapterSpec
	}
	if len(spec.Projections) == 0 || len(spec.Projections) > 8192 || spec.PreludeWidth < 0 || spec.PreludeWidth > 1<<20 || spec.PreludeBlocks > 0 && (spec.PreludeWidth == 0 || math.IsNaN(spec.PreludeLow) || math.IsNaN(spec.PreludeHigh) || math.IsInf(spec.PreludeLow, 0) || math.IsInf(spec.PreludeHigh, 0) || spec.PreludeLow >= spec.PreludeHigh) {
		return nil, ErrInitialAdapterSpec
	}
	seen := map[string]bool{}
	var expectedElements int64
	for _, projection := range spec.Projections {
		if projection.Name == "" || seen[projection.Name] || projection.Input < 1 || projection.Input > 1<<20 || projection.Output < 1 || projection.Output > 1<<20 || projection.Rank < 1 || projection.Rank > 1<<20 {
			return nil, ErrInitialAdapterSpec
		}
		seen[projection.Name] = true
		expectedElements += (projection.Input + projection.Output) * projection.Rank
	}
	if expectedElements > 1<<30 {
		return nil, ErrInitialAdapterSpec
	}
	expected, err := hex.DecodeString(spec.ExpectedSHA256)
	if err != nil {
		return nil, fmt.Errorf("%w: malformed digest", ErrInitialAdapterSpec)
	}
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	generator, err := torch.NewCPUGenerator(spec.Seed)
	if err != nil {
		return nil, err
	}
	defer generator.Close()
	result := &InitialAdapter{Parameters: make([]InitialParameter, 0, len(spec.Projections)*2)}
	complete := false
	defer func() {
		if !complete {
			err = errors.Join(err, result.Close())
		}
	}()
	discard := func(shape []int64, low, high float64) error {
		if err := ctx.Err(); err != nil {
			return err
		}
		value, err := generator.Uniform(shape, low, high, torch.Float32)
		if err != nil {
			return err
		}
		return errors.Join(value.Close(), ctx.Err())
	}
	for block := 0; block < spec.PreludeBlocks; block++ {
		if err := discard([]int64{spec.PreludeWidth}, spec.PreludeLow, spec.PreludeHigh); err != nil {
			return nil, err
		}
	}
	digest := sha256.New()
	var elements int64
	for _, projection := range spec.Projections {
		if err := discard([]int64{projection.Rank, projection.Input}, -1/math.Sqrt(float64(projection.Input)), 1/math.Sqrt(float64(projection.Input))); err != nil {
			return nil, err
		}
		if err := discard([]int64{projection.Output, projection.Rank}, -1/math.Sqrt(float64(projection.Rank)), 1/math.Sqrt(float64(projection.Rank))); err != nil {
			return nil, err
		}
		for _, letter := range []string{"A", "B"} {
			if err := ctx.Err(); err != nil {
				return nil, err
			}
			shape := []int64{projection.Rank, projection.Input}
			var value *torch.Tensor
			if letter == "A" {
				value, err = generator.Uniform(shape, -1/math.Sqrt(float64(projection.Input)), 1/math.Sqrt(float64(projection.Input)), torch.Float32)
			} else {
				shape = []int64{projection.Output, projection.Rank}
				value, err = torch.FromFloat32(make([]float32, projection.Output*projection.Rank), shape, torch.CPUDevice(), false)
			}
			if err != nil {
				return nil, err
			}
			name := fmt.Sprintf("%s.lora_%s.default.weight", projection.Name, letter)
			// Take ownership immediately so every later failure closes it.
			result.Parameters = append(result.Parameters, InitialParameter{Name: name, Value: value})
			leaf, err := value.SetRequiresGrad(true)
			if err != nil {
				return nil, err
			}
			result.Parameters[len(result.Parameters)-1].Value = leaf
			if err := value.Close(); err != nil {
				// Close is idempotent; retry the old handle on the failure path.
				return nil, errors.Join(err, value.Close())
			}
			info, err := leaf.Info()
			if err != nil {
				return nil, err
			}
			if info.DType != torch.Float32 || info.Device != torch.CPUDevice() || !info.RequiresGrad || !sameShape(info.Shape, shape) || info.Elements != shape[0]*shape[1] {
				return nil, errors.New("decoder: initial adapter tensor metadata differs")
			}
			finite, err := leaf.AllFinite()
			if err != nil || !finite {
				return nil, errors.Join(errors.New("decoder: nonfinite initial adapter tensor"), err)
			}
			content, err := leaf.Bytes()
			if err != nil {
				return nil, err
			}
			if int64(len(content)) != info.Elements*4 {
				return nil, errors.New("decoder: initial adapter tensor byte count differs")
			}
			if letter == "B" {
				for _, b := range content {
					if b != 0 {
						return nil, errors.New("decoder: initial adapter B must contain exact positive zeros")
					}
				}
			}
			_, _ = digest.Write([]byte(name))
			_, _ = digest.Write(content)
			elements += info.Elements
			if err := ctx.Err(); err != nil {
				return nil, err
			}
		}
	}
	if len(result.Parameters) != len(spec.Projections)*2 || elements != expectedElements {
		return nil, errors.New("decoder: initial adapter geometry differs")
	}
	observed := digest.Sum(nil)
	if !bytes.Equal(observed, expected) {
		return nil, ErrInitialAdapterIdentity
	}
	result.SHA256 = hex.EncodeToString(observed)
	if err := generator.Close(); err != nil {
		return nil, err
	}
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	complete = true
	return result, nil
}
