package ornith

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"strings"

	"github.com/tayi-ai/arandu-llama/training/torch"
)

// ErrInitialAdapterSpec identifies an absent identity or invalid bounded input.
var ErrInitialAdapterSpec = errors.New("ornith: invalid initial adapter specification")

// ErrInitialAdapterIdentity means generated bytes differ from the caller's
// mandatory expected digest. No tensors are returned on this failure.
var ErrInitialAdapterIdentity = errors.New("ornith: initial adapter identity differs")

// InitialAdapterSpec supplies every variable input to the reference initializer.
// The recipe owner must admit Seed, PreludeBlocks and ExpectedSHA256 together.
// The measured reference uses seed 83 and 24 blocks, each discarding 32 FP32 draws.
// PreludeBlocks is bounded to 0..24. ExpectedSHA256 must be 64 lowercase hex digits;
// there is no default or fallback identity.
type InitialAdapterSpec struct {
	Seed           uint64
	PreludeBlocks  int
	ExpectedSHA256 string
}

// InitialParameter owns one named, trainable FP32 CPU leaf. Names follow the
// preserved PEFT namespace; the caller owns any later placement or conversion.
type InitialParameter struct {
	Name  string
	Value *torch.Tensor
}

// InitialAdapter owns 32 reference-shaped tensors, totaling 557056 parameters.
// SHA256 hashes each UTF-8 name followed by its contiguous FP32 CPU bytes, in
// parameter order (layer, q/v projection, A/B). It qualifies initial bytes only.
type InitialAdapter struct {
	Parameters []InitialParameter
	SHA256     string
}

// Close releases every owned parameter and is idempotent, including nil values.
func (a *InitialAdapter) Close() error {
	if a == nil {
		return nil
	}
	var failures []error
	for _, parameter := range a.Parameters {
		failures = append(failures, parameter.Value.Close())
	}
	a.Parameters = nil
	return errors.Join(failures...)
}

// InitializeAdapter reproduces the measured CPU PEFT initialization schedule
// using a private native generator, without changing the default random stream.
// Geometry is explicit and fixed: layers 3,7,...31; rank 4; input 4096; query 8192
// and value 1024 outputs. Per projection it consumes constructor A then B, resets
// A with Kaiming's 1/sqrt(4096) bound, and constructs exact positive-zero B.
//
// The prelude reproduces Qwen3.5's post-load _init_weights RHS evaluations: each
// GDN builds 32 random values before init.copy_ skips its already-loaded A_log.
// This happens after leaving the meta/Float16 construction context, hence CPU
// FP32 in the reference loader. Native versions are not assumed equivalent:
// only an exact caller-supplied digest permits a result to escape.
// Source: Transformers v5.16.1 modeling_qwen3_5.py, _init_weights (lines 743-751).
// Cancellation is checked between native operations, not inside a running one.
func InitializeAdapter(ctx context.Context, spec InitialAdapterSpec) (_ *InitialAdapter, err error) {
	if ctx == nil || spec.PreludeBlocks < 0 || spec.PreludeBlocks > 24 || len(spec.ExpectedSHA256) != 64 || strings.ToLower(spec.ExpectedSHA256) != spec.ExpectedSHA256 {
		return nil, ErrInitialAdapterSpec
	}
	expected, err := hex.DecodeString(spec.ExpectedSHA256)
	if err != nil {
		return nil, fmt.Errorf("%w: malformed digest", ErrInitialAdapterSpec)
	}
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	generator, err := torch.NewCPUGenerator(spec.Seed)
	if err != nil {
		return nil, err
	}
	defer generator.Close()
	result := &InitialAdapter{Parameters: make([]InitialParameter, 0, 32)}
	complete := false
	defer func() {
		if !complete {
			err = errors.Join(err, result.Close())
		}
	}()
	discard := func(shape []int64, low, high float64) error {
		if err := ctx.Err(); err != nil {
			return err
		}
		value, err := generator.Uniform(shape, low, high, torch.Float32)
		if err != nil {
			return err
		}
		return errors.Join(value.Close(), ctx.Err())
	}
	for block := 0; block < spec.PreludeBlocks; block++ {
		if err := discard([]int64{32}, .01, 16); err != nil {
			return nil, err
		}
	}
	digest := sha256.New()
	var elements int64
	for layer := 3; layer < 32; layer += 4 {
		for _, projection := range []struct {
			name string
			out  int64
		}{{"q_proj", 8192}, {"v_proj", 1024}} {
			if err := discard([]int64{4, 4096}, -1.0/64, 1.0/64); err != nil {
				return nil, err
			}
			if err := discard([]int64{projection.out, 4}, -.5, .5); err != nil {
				return nil, err
			}
			for _, letter := range []string{"A", "B"} {
				if err := ctx.Err(); err != nil {
					return nil, err
				}
				shape := []int64{4, 4096}
				var value *torch.Tensor
				if letter == "A" {
					value, err = generator.Uniform(shape, -1.0/64, 1.0/64, torch.Float32)
				} else {
					shape = []int64{projection.out, 4}
					value, err = torch.FromFloat32(make([]float32, projection.out*4), shape, torch.CPUDevice(), false)
				}
				if err != nil {
					return nil, err
				}
				name := fmt.Sprintf("base_model.model.model.language_model.layers.%d.self_attn.%s.lora_%s.default.weight", layer, projection.name, letter)
				// Take ownership immediately so every later failure closes it.
				result.Parameters = append(result.Parameters, InitialParameter{Name: name, Value: value})
				leaf, err := value.SetRequiresGrad(true)
				if err != nil {
					return nil, err
				}
				result.Parameters[len(result.Parameters)-1].Value = leaf
				if err := value.Close(); err != nil {
					// Close is idempotent; retry the old handle on the failure path.
					return nil, errors.Join(err, value.Close())
				}
				info, err := leaf.Info()
				if err != nil {
					return nil, err
				}
				if info.DType != torch.Float32 || info.Device != torch.CPUDevice() || !info.RequiresGrad || !sameShape(info.Shape, shape) || info.Elements != shape[0]*shape[1] {
					return nil, errors.New("ornith: initial adapter tensor metadata differs")
				}
				finite, err := leaf.AllFinite()
				if err != nil || !finite {
					return nil, errors.Join(errors.New("ornith: nonfinite initial adapter tensor"), err)
				}
				content, err := leaf.Bytes()
				if err != nil {
					return nil, err
				}
				if int64(len(content)) != info.Elements*4 {
					return nil, errors.New("ornith: initial adapter tensor byte count differs")
				}
				if letter == "B" {
					for _, b := range content {
						if b != 0 {
							return nil, errors.New("ornith: initial adapter B must contain exact positive zeros")
						}
					}
				}
				_, _ = digest.Write([]byte(name))
				_, _ = digest.Write(content)
				elements += info.Elements
				if err := ctx.Err(); err != nil {
					return nil, err
				}
			}
		}
	}
	if len(result.Parameters) != 32 || elements != 557056 {
		return nil, errors.New("ornith: initial adapter geometry differs")
	}
	observed := digest.Sum(nil)
	if !bytes.Equal(observed, expected) {
		return nil, ErrInitialAdapterIdentity
	}
	result.SHA256 = hex.EncodeToString(observed)
	if err := generator.Close(); err != nil {
		return nil, err
	}
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	complete = true
	return result, nil
}
